// <auto-generated />
using System;
using HCB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCB.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260819043931_AddBondingModeFlags")]
    partial class AddBondingModeFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HCB.Data.Entity.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Action")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("LastRaisedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LastRaisedAt");

                    b.HasIndex("Name");

                    b.ToTable("Alarms", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.AlarmHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgeTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlarmId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.ToTable("AlarmHistory", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingAnalysis", b =>
                {
                    b.Property<int>("BondingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("P_HC_Fid_DX")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_HC_Fid_DY")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_HC_Fid_Dist")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_HC_Fid_L_X")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_HC_Fid_L_Y")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_HC_Fid_R_X")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_HC_Fid_R_Y")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_HC_Fid_Theta")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Align_DX")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Align_DY")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Align_Dist")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Align_Theta")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Fid_DX")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Fid_DY")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Fid_Dist")
                        .HasColumnType("REAL");

                    b.Property<double?>("P_PC_Fid_Theta")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_DX")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_DY")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_Dist")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_L_X")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_L_Y")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_R_X")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_R_Y")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Align_Theta")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_DX")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_DY")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_Dist")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_L_X")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_L_Y")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_R_X")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_R_Y")
                        .HasColumnType("REAL");

                    b.Property<double?>("W_HC_Fid_Theta")
                        .HasColumnType("REAL");

                    b.HasKey("BondingRecordId");

                    b.ToTable("BondingAnalysis", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingCoordinate", b =>
                {
                    b.Property<int>("BondingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BFL_X")
                        .HasColumnType("REAL");

                    b.Property<double>("BFL_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("BFR_X")
                        .HasColumnType("REAL");

                    b.Property<double>("BFR_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("BL_X")
                        .HasColumnType("REAL");

                    b.Property<double>("BL_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("BR_X")
                        .HasColumnType("REAL");

                    b.Property<double>("BR_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("TL_X")
                        .HasColumnType("REAL");

                    b.Property<double>("TL_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("TR_X")
                        .HasColumnType("REAL");

                    b.Property<double>("TR_Y")
                        .HasColumnType("REAL");

                    b.HasKey("BondingRecordId");

                    b.ToTable("BondingCoordinate", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingEquipment", b =>
                {
                    b.Property<int>("BondingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hc1Rad")
                        .HasColumnType("REAL");

                    b.Property<double>("Hc2Offset_X")
                        .HasColumnType("REAL");

                    b.Property<double>("Hc2Offset_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Hc2Rad")
                        .HasColumnType("REAL");

                    b.Property<double>("Hcro_X")
                        .HasColumnType("REAL");

                    b.Property<double>("Hcro_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("PcTRad")
                        .HasColumnType("REAL");

                    b.HasKey("BondingRecordId");

                    b.ToTable("BondingEquipment", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingMeasurement", b =>
                {
                    b.Property<int>("BondingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BtmLA_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("BtmLA_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("BtmLF_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("BtmLF_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("BtmRA_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("BtmRA_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("BtmRF_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("BtmRF_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLA_CenterX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLA_CenterY")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLA_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLA_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLA_StageX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLA_StageY")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLF_CenterX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLF_CenterY")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLF_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLF_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLF_StageX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopLF_StageY")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRA_CenterX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRA_CenterY")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRA_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRA_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRA_StageX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRA_StageY")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRF_CenterX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRF_CenterY")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRF_DxCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRF_DyCam")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRF_StageX")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopRF_StageY")
                        .HasColumnType("REAL");

                    b.HasKey("BondingRecordId");

                    b.ToTable("BondingMeasurement", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<bool>("AvgMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("TracingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Use2DMapping")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBtmIndividualMeasure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseFiducialTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseRightFidSimilarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("ParentRecordId");

                    b.HasIndex("Time");

                    b.ToTable("BondingRecord", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingResult", b =>
                {
                    b.Property<int>("BondingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ResultT")
                        .HasColumnType("REAL");

                    b.Property<double>("ResultX")
                        .HasColumnType("REAL");

                    b.Property<double>("ResultY")
                        .HasColumnType("REAL");

                    b.Property<double?>("Vernier_OffsetT")
                        .HasColumnType("REAL");

                    b.Property<double?>("Vernier_OffsetX")
                        .HasColumnType("REAL");

                    b.Property<double?>("Vernier_OffsetY")
                        .HasColumnType("REAL");

                    b.HasKey("BondingRecordId");

                    b.ToTable("BondingResult", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingSetting", b =>
                {
                    b.Property<int>("BondingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OffsetT")
                        .HasColumnType("REAL");

                    b.Property<double>("OffsetX")
                        .HasColumnType("REAL");

                    b.Property<double>("OffsetY")
                        .HasColumnType("REAL");

                    b.HasKey("BondingRecordId");

                    b.ToTable("BondingSetting", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.ECParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Maximum")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Minimum")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ECParam", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.IoDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IoDataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentDeviceId");

                    b.ToTable("IoData", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.IoDeviceDetail", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IoDeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId");

                    b.ToTable("IoDeviceDetail");
                });

            modelBuilder.Entity("HCB.Data.Entity.LogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceContext")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionDeviceDetail", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotionDeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId");

                    b.ToTable("MotionDeviceDetail");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EncoderCountsPerUnit")
                        .HasColumnType("REAL");

                    b.Property<int>("HommingProgramNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaximumLocation")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumLocation")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("MotorNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentDeviceId");

                    b.ToTable("Motion", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StringValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MotionParameter");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Speed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("MotionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MotionPosition", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int>("Component")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("UX_Recipes_OnlyOneActive")
                        .HasFilter("IsActive = 1");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.RecipeParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Maximum")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Minimum")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeParam", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.RoleManageRole", b =>
                {
                    b.Property<int>("ManagerRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("ManagerRoleId", "TargetRoleId");

                    b.HasIndex("TargetRoleId");

                    b.ToTable("RoleManageRole", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.RoleScreenAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<bool>("Granted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.HasIndex("RoleId", "ScreenId")
                        .IsUnique()
                        .HasDatabaseName("UX_RoleScreen_Pair");

                    b.ToTable("RoleScreenAccess", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Screens", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.StepRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int>("AccTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("AccTime2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ContTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<double>("Current")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Current2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("DecTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("LoadCell")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VacOffTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("StepRecipe", (string)null);
                });

            modelBuilder.Entity("HCB.Data.Entity.AlarmHistory", b =>
                {
                    b.HasOne("HCB.Data.Entity.Alarm", "Alarm")
                        .WithMany()
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingAnalysis", b =>
                {
                    b.HasOne("HCB.Data.Entity.BondingRecord", "BondingRecord")
                        .WithOne("Analysis")
                        .HasForeignKey("HCB.Data.Entity.BondingAnalysis", "BondingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BondingRecord");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingCoordinate", b =>
                {
                    b.HasOne("HCB.Data.Entity.BondingRecord", "BondingRecord")
                        .WithOne("Coordinate")
                        .HasForeignKey("HCB.Data.Entity.BondingCoordinate", "BondingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BondingRecord");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingEquipment", b =>
                {
                    b.HasOne("HCB.Data.Entity.BondingRecord", "BondingRecord")
                        .WithOne("Equipment")
                        .HasForeignKey("HCB.Data.Entity.BondingEquipment", "BondingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BondingRecord");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingMeasurement", b =>
                {
                    b.HasOne("HCB.Data.Entity.BondingRecord", "BondingRecord")
                        .WithOne("Measurement")
                        .HasForeignKey("HCB.Data.Entity.BondingMeasurement", "BondingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BondingRecord");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingRecord", b =>
                {
                    b.HasOne("HCB.Data.Entity.BondingRecord", "Parent")
                        .WithMany("ReMeasures")
                        .HasForeignKey("ParentRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingResult", b =>
                {
                    b.HasOne("HCB.Data.Entity.BondingRecord", "BondingRecord")
                        .WithOne("Result")
                        .HasForeignKey("HCB.Data.Entity.BondingResult", "BondingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BondingRecord");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingSetting", b =>
                {
                    b.HasOne("HCB.Data.Entity.BondingRecord", "BondingRecord")
                        .WithOne("Setting")
                        .HasForeignKey("HCB.Data.Entity.BondingSetting", "BondingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BondingRecord");
                });

            modelBuilder.Entity("HCB.Data.Entity.IoDataEntity", b =>
                {
                    b.HasOne("HCB.Data.Entity.IoDeviceDetail", "ParentDeviceEntity")
                        .WithMany("IoDataList")
                        .HasForeignKey("ParentDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDeviceEntity");
                });

            modelBuilder.Entity("HCB.Data.Entity.IoDeviceDetail", b =>
                {
                    b.HasOne("HCB.Data.Entity.Device", "Device")
                        .WithOne("IoDeviceDetail")
                        .HasForeignKey("HCB.Data.Entity.IoDeviceDetail", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionDeviceDetail", b =>
                {
                    b.HasOne("HCB.Data.Entity.Device", "Device")
                        .WithOne("MotionDeviceDetail")
                        .HasForeignKey("HCB.Data.Entity.MotionDeviceDetail", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionEntity", b =>
                {
                    b.HasOne("HCB.Data.Entity.MotionDeviceDetail", "ParentDeviceEntity")
                        .WithMany("MotionList")
                        .HasForeignKey("ParentDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDeviceEntity");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionParameter", b =>
                {
                    b.HasOne("HCB.Data.Entity.MotionEntity", "Motion")
                        .WithMany("ParameterList")
                        .HasForeignKey("MotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motion");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionPosition", b =>
                {
                    b.HasOne("HCB.Data.Entity.MotionEntity", "Motion")
                        .WithMany("PositionList")
                        .HasForeignKey("MotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Motion");
                });

            modelBuilder.Entity("HCB.Data.Entity.RecipeParam", b =>
                {
                    b.HasOne("HCB.Data.Entity.Recipe", "Recipe")
                        .WithMany("ParamList")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HCB.Data.Entity.RoleManageRole", b =>
                {
                    b.HasOne("HCB.Data.Entity.Role", "Manager")
                        .WithMany("ManageTargets")
                        .HasForeignKey("ManagerRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCB.Data.Entity.Role", "Target")
                        .WithMany("ManagedBy")
                        .HasForeignKey("TargetRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("HCB.Data.Entity.RoleScreenAccess", b =>
                {
                    b.HasOne("HCB.Data.Entity.Role", "Role")
                        .WithMany("ScreenAccesses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCB.Data.Entity.Screen", "Screen")
                        .WithMany("AccessBy")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("HCB.Data.Entity.StepRecipe", b =>
                {
                    b.HasOne("HCB.Data.Entity.Recipe", "Recipe")
                        .WithMany("StepList")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HCB.Data.Entity.BondingRecord", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("Coordinate");

                    b.Navigation("Equipment");

                    b.Navigation("Measurement");

                    b.Navigation("ReMeasures");

                    b.Navigation("Result");

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("HCB.Data.Entity.Device", b =>
                {
                    b.Navigation("IoDeviceDetail");

                    b.Navigation("MotionDeviceDetail");
                });

            modelBuilder.Entity("HCB.Data.Entity.IoDeviceDetail", b =>
                {
                    b.Navigation("IoDataList");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionDeviceDetail", b =>
                {
                    b.Navigation("MotionList");
                });

            modelBuilder.Entity("HCB.Data.Entity.MotionEntity", b =>
                {
                    b.Navigation("ParameterList");

                    b.Navigation("PositionList");
                });

            modelBuilder.Entity("HCB.Data.Entity.Recipe", b =>
                {
                    b.Navigation("ParamList");

                    b.Navigation("StepList");
                });

            modelBuilder.Entity("HCB.Data.Entity.Role", b =>
                {
                    b.Navigation("ManageTargets");

                    b.Navigation("ManagedBy");

                    b.Navigation("ScreenAccesses");
                });

            modelBuilder.Entity("HCB.Data.Entity.Screen", b =>
                {
                    b.Navigation("AccessBy");
                });
#pragma warning restore 612, 618
        }
    }
}
